// Memory summarization via local Ollama (v0.4 thesis #2).
//
// Two summaries per memory:
//   one-liner (≤20 words) for list cells, CLI output, MCP responses
//   paragraph (≤80 words) for detail panels and richer MCP modes
//
// Both are generated by `llama3.2:3b` (or the user-configured model) and
// cached in memory_summaries keyed by content_hash. If Ollama or the model
// is unreachable, every function here resolves to null silently — same
// graceful-degradation pattern as embeddings.

import { createHash } from 'crypto'
import log from 'electron-log'

const OLLAMA_URL = process.env.OLLAMA_URL || 'http://127.0.0.1:11434'
const SUMMARY_MODEL = process.env.CORTEX_SUMMARY_MODEL || 'llama3.2:3b'
const MAX_INPUT_CHARS = 6000
const HEALTH_TIMEOUT_MS = 2000
const GEN_TIMEOUT_MS = 30_000

const ONE_LINE_SYSTEM = `You write extremely concise one-line summaries of conversations and notes.
Output ONE line, max 20 words, no preamble, no quotes, no trailing punctuation.
Capture the SUBJECT and OUTCOME. Not "this is about X" — directly state X.`

const PARAGRAPH_SYSTEM = `You write tight paragraph summaries of conversations and notes.
Output ONE paragraph, max 80 words, no headings, no lists, no preamble.
Lead with the topic, then the key points, then what was decided or learned.`

/** SHA-1 of trimmed title + content. The summary cache invalidates on change. */
export function contentHash(title: string, content: string): string {
  const h = createHash('sha1')
  h.update(title.trim())
  h.update('\n')
  h.update(content.trim())
  return h.digest('hex')
}

export function isFresh(currentHash: string, cachedHash: string | null | undefined): boolean {
  return cachedHash != null && cachedHash === currentHash
}

/** Probe used by the digest / backfill workers before queueing work. */
export async function isSummaryModelAvailable(): Promise<boolean> {
  try {
    const r = await fetch(`${OLLAMA_URL}/api/tags`, { signal: AbortSignal.timeout(HEALTH_TIMEOUT_MS) })
    if (!r.ok) return false
    const body = await r.json() as { models?: Array<{ name?: string }> }
    return (body.models ?? []).some(m => typeof m.name === 'string' && m.name.startsWith(SUMMARY_MODEL))
  } catch {
    return false
  }
}

/** Truncate to MAX_INPUT_CHARS at a word boundary so we don't slice mid-token. */
export function clampInput(text: string): string {
  if (text.length <= MAX_INPUT_CHARS) return text
  const cut = text.lastIndexOf(' ', MAX_INPUT_CHARS)
  return text.slice(0, cut > MAX_INPUT_CHARS / 2 ? cut : MAX_INPUT_CHARS)
}

/** Strip the leading "Here's a summary:" / "Sure!" prefix the smaller models love. */
export function cleanOutput(text: string, oneLine: boolean): string {
  let out = (text ?? '').trim()
  out = out.replace(/^["']|["']$/g, '')
  out = out.replace(/^(sure|certainly|of course|absolutely)[!.,]?\s*/i, '')
  out = out.replace(/^(here(?:'|')?s? (?:is )?(?:a |the )?(?:concise |brief |short |one-line )?summary[:.]?\s*)/i, '')
  out = out.replace(/^(summary|tl;?dr)[:.]?\s*/i, '')
  if (oneLine) {
    // Take the first line only; collapse newlines.
    out = out.split(/\r?\n/)[0]?.trim() ?? ''
    out = out.replace(/[.!?]$/, '')
  } else {
    // Collapse paragraph whitespace; cap word count.
    out = out.replace(/\s+/g, ' ').trim()
  }
  return out
}

/** Hard word cap as a safety net — Ollama models routinely overshoot. */
export function capWords(text: string, maxWords: number): string {
  const words = text.split(/\s+/).filter(Boolean)
  if (words.length <= maxWords) return text
  return words.slice(0, maxWords).join(' ') + '…'
}

interface OllamaGenerate {
  model: string
  prompt: string
  system: string
  stream?: boolean
  options?: { temperature?: number; num_predict?: number; top_p?: number }
}

async function generate(req: OllamaGenerate): Promise<string | null> {
  try {
    const r = await fetch(`${OLLAMA_URL}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...req, stream: false }),
      signal: AbortSignal.timeout(GEN_TIMEOUT_MS),
    })
    if (!r.ok) {
      log.warn(`[summarize] ollama responded ${r.status}`)
      return null
    }
    const body = await r.json() as { response?: string }
    return typeof body.response === 'string' ? body.response : null
  } catch (err) {
    log.warn('[summarize] request failed:', err)
    return null
  }
}

export async function summarizeMemory(
  title: string,
  content: string,
): Promise<{ oneLine: string | null; paragraph: string | null; model: string }> {
  const text = clampInput(`Title: ${title}\n\n${content}`.trim())
  if (!text) return { oneLine: null, paragraph: null, model: SUMMARY_MODEL }

  const [oneLineRaw, paragraphRaw] = await Promise.all([
    generate({
      model: SUMMARY_MODEL,
      system: ONE_LINE_SYSTEM,
      prompt: text,
      options: { temperature: 0.2, num_predict: 60, top_p: 0.9 },
    }),
    generate({
      model: SUMMARY_MODEL,
      system: PARAGRAPH_SYSTEM,
      prompt: text,
      options: { temperature: 0.3, num_predict: 200, top_p: 0.9 },
    }),
  ])

  const oneLine = oneLineRaw ? capWords(cleanOutput(oneLineRaw, true), 20) : null
  const paragraph = paragraphRaw ? capWords(cleanOutput(paragraphRaw, false), 80) : null
  return { oneLine, paragraph, model: SUMMARY_MODEL }
}
